// <auto-generated />
using System;
using EMPLOYEEPROJECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMPLOYEEPROJECT.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20190929144513_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMPLOYEEPROJECT.Models.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<DateTime>("DateTimeUpdated");

                    b.Property<Guid>("LastTimeUpdated");

                    b.Property<string>("Name");

                    b.Property<long>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EMPLOYEEPROJECT.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<DateTime>("DateTimeUpdated");

                    b.Property<string>("Firstname");

                    b.Property<Guid>("LastTimeUpdated");

                    b.Property<string>("Lastname");

                    b.Property<long>("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EMPLOYEEPROJECT.Models.EmployeeDepartmentRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedBy");

                    b.Property<DateTime>("DateTimeCreated");

                    b.Property<DateTime>("DateTimeUpdated");

                    b.Property<long>("DepartmentId");

                    b.Property<long>("EmployeeId");

                    b.Property<Guid>("LastTimeUpdated");

                    b.Property<long>("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDepartmentRelations");
                });

            modelBuilder.Entity("EMPLOYEEPROJECT.Models.EmployeeDepartmentRelation", b =>
                {
                    b.HasOne("EMPLOYEEPROJECT.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EMPLOYEEPROJECT.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
